services:
  vpn:
    image: dperson/openvpn-client
    container_name: vpn
    restart: unless-stopped
    network_mode: bridge
    cap_add:
      - net_admin
    ports:
      # - 8112:8112 # Deluge
      # - 58846:58846 # Deluge daemon
      # - 6881:6881/udp # Deluge inbound torrent traffic
      # - 6881:6881/tcp # Deluge inbound torrent traffic
      - 8090:8090 # qBittorrent
      - 6887:6887/udp # qBittorrent inbound torrent traffic
      - 6887:6887/tcp # qBittorrent inbound torrent traffic
      # - 9117:9117 # Jackett
      - 9696:9696 # Prowlarr
      # - 8989:8989 # Sonarr
      # - 7878:7878 # Radarr
      # - 8686:8686 # Lidarr
    volumes:
      - ../../Volumes/vpn/vpn:/vpn
    command: '-f ""'