services:
  vpn:
    image: dperson/openvpn-client
    container_name: vpn
    restart: unless-stopped
    network_mode: bridge
    cap_add:
      - net_admin
    ports:
      - 8090:8090 # qBittorrent
      - 6887:6881/udp # qBittorrent inbound traffic
      - 6887:6881/tcp # qBittorrent inbound traffic
      - 9696:9696 # Prowlarr 
      - 5031:5031 # Soulseek
      - 53199:53199 # Soulseek inbound traffic
      # - 8112:8112 # Deluge
      # - 58846:58846 # Deluge daemon
      # - 6881:6881/udp # Deluge inbound traffic
      # - 6881:6881/tcp # Deluge inbound traffic
      # - 9117:9117 # Jackett
      # - 8989:8989 # Sonarr
      # - 7878:7878 # Radarr
      # - 8686:8686 # Lidarr
    volumes:
      - ../../Volumes/vpn/data:/vpn
    command: '-f ""'
