services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: container:vpn
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8090
      - TORRENTING_PORT=6887
    volumes:
      - ../../Volumes/qbittorrent/config:/config
      - /mnt/drive1/Media/Torrents:/downloads