services:
  pterodactyl-database:
    image: mariadb:10.5
    container_name: pterodactyl-database
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ../../Volumes/pterodactyl-database/database:/var/lib/mysql
    environment:
      MYSQL_USER: pterodactyl
      MYSQL_PASSWORD: pterodactyl
      MYSQL_ROOT_PASSWORD: pterodactyl
      MYSQL_DATABASE: pterodactyl
  pterodactyl-cache:
    image: redis:alpine
    container_name: pterodactyl-cache
    restart: unless-stopped
  pterodactyl-panel:
    image: ghcr.io/pterodactyl/panel
    container_name: pterodactyl-panel
    restart: unless-stopped
    ports:
      - 5700:80
      - 5701:443
    volumes:
      - ../../Volumes/pterodactyl-panel/var:/app/var
      - ../../Volumes/pterodactyl-panel/nginx:/app/nginx/http.d
      - ../../Volumes/pterodactyl-panel/certs:/app/letsencrypt
      - ../../Volumes/pterodactyl-panel/logs:/app/storage/logs
    environment:
      APP_ENV: production
      APP_ENVIRONMENT_ONLY: false
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: pterodactyl-cache
      DB_HOST: pterodactyl-database
      DB_PORT: 3306
      DB_DATABASE: pterodactyl
      DB_USERNAME: pterodactyl
      DB_PASSWORD: pterodactyl
  pterodactyl-wings:
    image: ghcr.io/pterodactyl/wings
    container_name: pterodactyl-wings
    restart: unless-stopped
    networks:
      - pterodactyl-wings
    ports:
      - 5702:8080
      - 5703:2022
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - ../../Volumes/pterodactyl-wings/etc:/etc/pterodactyl
      - ../../Volumes/pterodactyl-wings/lib:/var/lib/pterodactyl
      - ../../Volumes/pterodactyl-wings/logs:/var/log/pterodactyl
      - ../../Volumes/pterodactyl-wings/temp:/tmp/pterodactyl
      - ../../Volumes/pterodactyl-wings/certs:/etc/ssl/certs
networks:
  pterodactyl-wings:
    name: pterodactyl-wings
    driver: bridge
    ipam:
      config:
        - subnet: "172.21.0.0/16"