services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 5055:5055
    volumes:
      - ../../Volumes/jellyseerr/config:/app/config
