services:
  template:
    image: template
    container_name: template
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 80:80
    volumes:
      - ../../Volumes/template/config:/config
