services:
  feishin:
    image: ghcr.io/jeffvli/feishin:latest
    container_name: feishin
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 9180:9180
    environment:
      - SERVER_NAME=Navidrome
      - SERVER_LOCK=true
      - SERVER_TYPE=navidrome
      - SERVER_URL=https://navidrome.ddns.lyall.lol
