services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 3500:3000
    volumes:
      - ./Volumes/homepage/config:/app/config
      - ./Volumes/homepage/assets:/app/public/assets
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "*"
