services:
  feishin:
    image: ghcr.io/jeffvli/feishin:latest
    container_name: feishin
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 9180:9180
    env_file:
      - ../../Volumes/feishin/.env
    environment:
      - SERVER_LOCK=true
      - SERVER_TYPE=navidrome
      - LEGACY_AUTHENTICATION=false
      - ANALYTICS_DISABLED=false
