services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 4533:4533
    volumes:
      - ../../Volumes/navidrome/data:/data
      - /mnt/drive1/Media/Music:/music:ro
      - /mnt/drive1/Media/Music 2:/music-2:ro
      - /mnt/drive1/Media/Music 3:/music-3:ro
    environment:
      - ND_CONFIGFILE=/data/navidrome.toml
