services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant
    container_name: home-assistant
    restart: unless-stopped
    network_mode: host
    volumes:
      - ../../Volumes/home-assistant/config:/config
      - /mnt/drive1/Media:/media
