services:
  radarr:
    image: ghcr.io/hotio/radarr
    container_name: radarr
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 7878:7878
    volumes:
      - ./Volumes/radarr/config:/config
      - /mnt/drive1/Media:/media
      - /mnt/drive1/Media/Torrents:/downloads