services:
  teamspeak:
    image: teamspeaksystems/teamspeak6-server
    container_name: teamspeak
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 9987:9987/udp
      - 30033:30033/tcp
    environment:
      - TSSERVER_LICENSE_ACCEPTED=accept
    volumes:
      - ./Volumes/teamspeak/data:/var/tsserver
