services:
  minecraft:
    image: openjdk:22-oracle
    container_name: minecraft
    restart: unless-stopped
    network_mode: bridge
    user: 1000:1000
    ports:
      - 25560-25570:25560-25570
    working_dir: /data
    command: bash ./run.sh
    stdin_open: true
    tty: true
    volumes:
      - ../../Volumes/minecraft/data:/data
