services:
  http-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: http-proxy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ../../Volumes/http-proxy/config.json:/data/config.json
      - ../../Volumes/http-proxy/services:/data/services
      - ../../Volumes/http-proxy/pages:/data/pages
      - ../../Volumes/certificate-renewer/config:/etc/letsencrypt
