services:
  http-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: http-proxy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ../../Volumes/http-proxy/config.json:/data/config.json
      - ../../Volumes/http-proxy/services:/data/services
      - ../../Volumes/http-proxy/pages:/data/pages
      # - ../../Volumes/http-proxy/cert.pem:/data/cert.pem
      # - ../../Volumes/http-proxy/privkey.pem:/data/privkey.pem
      - ../../Volumes/certificate-renewer/config/live/lyall.lol/cert.pem:/data/cert.pem
      - ../../Volumes/certificate-renewer/config/live/lyall.lol/privkey.pem:/data/privkey.pem
      - ../../Volumes/certificate-renewer/config/live/lyall.lol/fullchain.pem:/data/fullchain.pem
      - ../../Volumes/certificate-renewer/config/live/lyall.lol/chain.pem:/data/chain.pem
