services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    network_mode: host
    volumes:
      - ../../Volumes/adguardhome/work:/opt/adguardhome/work
      - ../../Volumes/adguardhome/conf:/opt/adguardhome/conf