services:
  iptv-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iptv-proxy
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 4392:4392
    volumes:
      - ../../Volumes/iptv-proxy/config.json:/data/config.json
