services:
  roundcube:
    image: roundcube/roundcubemail
    container_name: roundcube
    restart: unless-stopped
    ports:
      - 8070:80
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=mysql
      - ROUNDCUBEMAIL_DB_HOST=roundcube_db
      - ROUNDCUBEMAIL_DB_NAME=roundcube
      - ROUNDCUBEMAIL_DB_USER=roundcube
      - ROUNDCUBEMAIL_DB_PASSWORD=roundcube
      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://imap.mail.me.com
      - ROUNDCUBEMAIL_DEFAULT_PORT=993
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://smtp.mail.me.com
      - ROUNDCUBEMAIL_SMTP_PORT=587
  roundcube_db:
    image: mysql
    container_name: roundcube_db
    restart: unless-stopped
    environment:
      - MYSQL_USER=roundcube
      - MYSQL_PASSWORD=roundcube
      - MYSQL_DATABASE=roundcube
      - MYSQL_ROOT_PASSWORD=roundcube
    volumes:
      - ../../Volumes/roundcube_db/data:/var/lib/mysql
